# Dockerfile for running Fortran code on Debian Linux
# Author: Andrew Jarombek
# Date: 10/23/2022

FROM ajarombek/debian-system-programming:latest

LABEL maintainer="andrew@jarombek.com" \
      version="1.0.0" \
      description="Dockerfile for running the Fortran code on Debian Linux"

RUN apt-get -y install gfortran