# GitHub Action for running C code samples.
# Author: Andrew Jarombek
# Date: 10/22/2022

name: LLVM

on:
  push:
    branches: ["master", "feature/*"]
  pull_request:
    branches: ["master"]

  schedule:
    - cron: "0 5 * * 5"

  workflow_dispatch:

jobs:
  llvm:
    runs-on: ubuntu-latest
    container: ajarombek/debian-system-programming:latest
    steps:
      - run: echo "Job running on a ${{ runner.os }} server"

      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "Checked out branch '${{ github.ref }}' of the ${{ github.repository }} repository"

      - name: Build and Run C Code
        run: cd C && cmake . && cmake --build . && ./matrices