# GitHub Action for running Fortran code samples.
# Author: Andrew Jarombek
# Date: 10/23/2022

name: Fortran

on:
  push:
    branches: ["master", "feature/*"]
  pull_request:
    branches: ["master"]

  schedule:
    - cron: "0 5 * * 5"

  workflow_dispatch:

jobs:
  fortran:
    runs-on: ubuntu-latest
    container: ajarombek/data-analytics-prototypes-fortran:latest
    steps:
      - run: echo "Job running on a ${{ runner.os }} server"

      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "Checked out branch '${{ github.ref }}' of the ${{ github.repository }} repository"

      - name: Build and Run Fortran Code
        run: >
          cd Fortran && 
          cmake . && 
          cmake --build . && 
          ./hello_world && 
          ./basics && 
          ./matrices